# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x10\x66\x61issrpc_service\"&\n\x0bMessage_add\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03\x65mb\x18\x02 \x01(\t\"\x0e\n\x0cMessage_None\"\x1a\n\x0bMessage_int\x12\x0b\n\x03num\x18\x01 \x01(\x03\"/\n\x0eMessage_recall\x12\x0f\n\x07his_ids\x18\x01 \x01(\t\x12\x0c\n\x04topk\x18\x02 \x01(\x05\" \n\x0cMessage_json\x12\x10\n\x08json_str\x18\x01 \x01(\t\"/\n\x0bMessage_cal\x12\x0f\n\x07his_ids\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61l_ids\x18\x02 \x01(\t\"\x1a\n\x0bMessage_tag\x12\x0b\n\x03tag\x18\x01 \x01(\t2\xda\x03\n\x0c\x46\x61issService\x12\x45\n\x03\x61\x64\x64\x12\x1d.faissrpc_service.Message_add\x1a\x1d.faissrpc_service.Message_tag\"\x00\x12H\n\x06remove\x12\x1d.faissrpc_service.Message_int\x1a\x1d.faissrpc_service.Message_tag\"\x00\x12K\n\x08get_size\x12\x1e.faissrpc_service.Message_None\x1a\x1d.faissrpc_service.Message_int\"\x00\x12S\n\rrecall_by_ids\x12 .faissrpc_service.Message_recall\x1a\x1e.faissrpc_service.Message_json\"\x00\x12M\n\ncal_by_ids\x12\x1d.faissrpc_service.Message_cal\x1a\x1e.faissrpc_service.Message_json\"\x00\x12H\n\x05write\x12\x1e.faissrpc_service.Message_None\x1a\x1d.faissrpc_service.Message_tag\"\x00\x62\x06proto3')



_MESSAGE_ADD = DESCRIPTOR.message_types_by_name['Message_add']
_MESSAGE_NONE = DESCRIPTOR.message_types_by_name['Message_None']
_MESSAGE_INT = DESCRIPTOR.message_types_by_name['Message_int']
_MESSAGE_RECALL = DESCRIPTOR.message_types_by_name['Message_recall']
_MESSAGE_JSON = DESCRIPTOR.message_types_by_name['Message_json']
_MESSAGE_CAL = DESCRIPTOR.message_types_by_name['Message_cal']
_MESSAGE_TAG = DESCRIPTOR.message_types_by_name['Message_tag']
Message_add = _reflection.GeneratedProtocolMessageType('Message_add', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_ADD,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_add)
  })
_sym_db.RegisterMessage(Message_add)

Message_None = _reflection.GeneratedProtocolMessageType('Message_None', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_NONE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_None)
  })
_sym_db.RegisterMessage(Message_None)

Message_int = _reflection.GeneratedProtocolMessageType('Message_int', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_INT,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_int)
  })
_sym_db.RegisterMessage(Message_int)

Message_recall = _reflection.GeneratedProtocolMessageType('Message_recall', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_RECALL,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_recall)
  })
_sym_db.RegisterMessage(Message_recall)

Message_json = _reflection.GeneratedProtocolMessageType('Message_json', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_JSON,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_json)
  })
_sym_db.RegisterMessage(Message_json)

Message_cal = _reflection.GeneratedProtocolMessageType('Message_cal', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_CAL,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_cal)
  })
_sym_db.RegisterMessage(Message_cal)

Message_tag = _reflection.GeneratedProtocolMessageType('Message_tag', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE_TAG,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:faissrpc_service.Message_tag)
  })
_sym_db.RegisterMessage(Message_tag)

_FAISSSERVICE = DESCRIPTOR.services_by_name['FaissService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE_ADD._serialized_start=32
  _MESSAGE_ADD._serialized_end=70
  _MESSAGE_NONE._serialized_start=72
  _MESSAGE_NONE._serialized_end=86
  _MESSAGE_INT._serialized_start=88
  _MESSAGE_INT._serialized_end=114
  _MESSAGE_RECALL._serialized_start=116
  _MESSAGE_RECALL._serialized_end=163
  _MESSAGE_JSON._serialized_start=165
  _MESSAGE_JSON._serialized_end=197
  _MESSAGE_CAL._serialized_start=199
  _MESSAGE_CAL._serialized_end=246
  _MESSAGE_TAG._serialized_start=248
  _MESSAGE_TAG._serialized_end=274
  _FAISSSERVICE._serialized_start=277
  _FAISSSERVICE._serialized_end=751
# @@protoc_insertion_point(module_scope)
